### ISSUE TITLE
Bitcoin Cash potentially lost after deposit address conversion with https://cashaddr.bitcoincash.org/

### ISSUE THREAD

**Issue by Voluntary-zcash** [schancel/cashaddr-converter#17]
*** Edit *** The problem is resolved - it was my mistake.  

The URL (https://cashaddr.bitcoincash.org/) was supplied by the Trezor wallet interface and I input my Binance Bitcoin Cash deposit address.  

The input address: 1HrdSCp6PfHtjthMQcZCB6BN3Wy6z8QA59
The output given was: qzuwfncx5asl7lr0t9ts3fr6z26dp0dszqydl4tdex

I don't believe that I've deposited Bitcoin Cash to my Binace account before but the above CashAddr has various other transactions.

**Comment by Voluntary-zcash** [comment]
Damn it...  I see my error.  I need new glasses.  I copied the donation address from the conversion page and unintentionally sent my Bitcoin Cash to it.  Could whoever owns that address contact me at voluntary-zcash@protonmail.com

**Comment by schancel** [comment]
I'm not sure I understand the issue.  The output given is the correct conversation.  Were you able to get your funds back from Binance?

**Comment by Farshidkhani** [comment]
1HrdSCp6PfHtjthMQcZCB6BN3Wy6z8QA59

**Comment by Farshidkhani** [comment]
1HrdSCp6PfHtjthMQcZCB6BN3Wy6z8QA59

**Comment by Farshidkhani** [comment]
1HrdSCp6PfHtjthMQcZCB6BN3Wy6z8QA59

**Comment by Farshidkhani** [comment]
1HrdSCp6PfHtjthMQcZCB6BN3Wy6z8QA59

**Comment by Farshidkhani** [comment]
nimasavarkhani84@gmail.com

**Comment by Farshidkhani** [comment]
nimasavarkhani84@gmail.com

**Comment by Farshidkhani** [comment]
nimasavarkhani84@gmail.com

**Comment by Farshidkhani** [comment]
nimasavarkhani84@gmail.com
